
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: library-php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - symfony

  web:
    image: nginx:latest
    container_name: library-web
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: library-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: library-phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony: